### ISSUE TITLE
import echarts from 'echarts/lib/echarts'" is not supported anymore.

### ISSUE THREAD

**Issue by 180and170** [ywwhack/babel-plugin-equire#7]
when i use equire  i got a bug ，the Echarts I used is 5.1.1。

`index.js:1451 "import echarts from 'echarts/lib/echarts'" is not supported anymore. Use "import * as echarts from 'echarts/lib/echarts'" instead; 
    at Tendency (http://localhost:3000/static/js/main.chunk.js:15006:5)
    at div
    at div
    at Spin (http://localhost:3000/static/js/vendors~main.chunk.js:97618:37)
    at div
    at div
    at Home (http://localhost:3000/static/js/main.chunk.js:15537:59)
    at Route (http://localhost:3000/static/js/vendors~main.chunk.js:286074:29)
    at Switch (http://localhost:3000/static/js/vendors~main.chunk.js:286276:29)
    at div
    at Container (http://localhost:3000/static/js/vendors~main.chunk.js:286983:5)
    at main
    at Basic (http://localhost:3000/static/js/vendors~main.chunk.js:90180:25)
    at Adapter (http://localhost:3000/static/js/vendors~main.chunk.js:90163:37)
    at section
    at BasicLayout (http://localhost:3000/static/js/vendors~main.chunk.js:90195:34)
    at Adapter (http://localhost:3000/static/js/vendors~main.chunk.js:90163:37)
    at section
    at BasicLayout (http://localhost:3000/static/js/vendors~main.chunk.js:90195:34)
    at Adapter (http://localhost:3000/static/js/vendors~main.chunk.js:90163:37)
    at div
    at Container (http://localhost:3000/static/js/vendors~main.chunk.js:286983:5)
    at section
    at BasicLayout (http://localhost:3000/static/js/vendors~main.chunk.js:90195:34)
    at Adapter (http://localhost:3000/static/js/vendors~main.chunk.js:90163:37)
    at Layouts (http://localhost:3000/static/js/main.chunk.js:11272:78)
    at Layout (http://localhost:3000/static/js/main.chunk.js:11495:1)
    at FormProvider (http://localhost:3000/static/js/vendors~main.chunk.js:189441:31)
    at LocaleProvider (http://localhost:3000/static/js/vendors~main.chunk.js:90623:37)
    at ProviderChildren (http://localhost:3000/static/js/vendors~main.chunk.js:82783:24)
    at LocaleReceiver (http://localhost:3000/static/js/vendors~main.chunk.js:90424:37)
    at ConfigProvider (http://localhost:3000/static/js/vendors~main.chunk.js:82890:13)
    at Router (http://localhost:3000/static/js/vendors~main.chunk.js:285709:30)
    at BrowserRouter (http://localhost:3000/static/js/vendors~main.chunk.js:285329:35)
    at PageFrame (http://localhost:3000/static/js/main.chunk.js:11850:1)
    at Provider (http://localhost:3000/static/js/vendors~main.chunk.js:283601:20)`

**Comment by lioilLRM** [comment]
同问

**Comment by lujunan1109** [comment]
降低echarts版本就好了，^4.8.0 自测没问题
